### ISSUE TITLE
RMV Profile

### ISSUE THREAD

**Issue by half-evil** [bergmannjg/fshafas#1]
Hi, 

thank you for your great efford! It's a good chance for me to learn some f# at last 😊

I'm trying to develop a profile for rmv.de, based on the bvg profile. But after connecting I get an authorization error: "HCI Core: Authorization fail". Do you know where I can get an AID? Do you know, if rmv permits the use of mgate.exe? I didn't find any information on the web.

Greetings,
Christian

**Comment by bergmannjg** [comment]
@half-evil, thank you for your interest in fsashas.

Fshafas is a port of the JavaScript [hafas-client library](https://github.com/public-transport/hafas-client) to F#.

Hafas-client has a [RMV profile](https://github.com/public-transport/hafas-client/tree/master/p/rmv) with the required data.
