### ISSUE TITLE
The package FsHafas.JavaScript 2.8.0 can't be found in ... 

### ISSUE THREAD

**Issue by RITE-X** [bergmannjg/fshafas#2]
I stuck with the problem The package FsHafas.JavaScript 2.8.0 can't be found in C:\Users\myUser\local.packages while trying to build the project on for every language (F#, JS, Python) As i understand this project has a references to local nuget packages that not incluted to repo. Can you provide it? 

source ~/local.packages

nuget FsHafas.JavaScript = 2.8.0
nuget FsHafas.Profiles.JavaScript = 2.8.0
nuget FsHafas.Python = 2.8.0-beta-0.0.28
nuget FsHafas.Profiles.Python = 2.8.0-beta-0.0.28

**Comment by bergmannjg** [comment]
The local nuget packages 

nuget FsHafas.JavaScript = 2.8.0
nuget FsHafas.Profiles.JavaScript = 2.8.0
nuget FsHafas.Python = 2.8.0-beta-0.0.28
nuget FsHafas.Profiles.Python = 2.8.0-beta-0.0.28

are used in the examples projects. The packages are built with

```sh
./build.sh JavaScript
```

and

```sh
./build.sh Python
```
The fshafas library can be used for several targets

* in a F# program that compiles to dotnet (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli))
* in a C# program that compiles to dotnet (see [csharp](https://github.com/bergmannjg/fshafas/blob/main/src/examples/fshafas.csharp/Program.cs))
* in a F# program that compiles to JavaScript, the nuget package FsHafas.JavaScript is required (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli)) 
* in a F# program that compiles to Python, the nuget package FsHafas.Python is required (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli)) 
* in a JavaScript program that uses the fshafas npm package (see [JS](https://github.com/bergmannjg/fshafas/tree/main/src/examples/fshafas.fable.node))
* in a Python program that uses the fshafas python package (see [Python](https://github.com/bergmannjg/fshafas/tree/main/src/examples/fshafas.fable.python))

How will you use the library?

I added the missing packages to the current release.

**Comment by RITE-X** [comment]
> The local nuget packages
> 
> nuget FsHafas.JavaScript = 2.8.0 nuget FsHafas.Profiles.JavaScript = 2.8.0 nuget FsHafas.Python = 2.8.0-beta-0.0.28 nuget FsHafas.Profiles.Python = 2.8.0-beta-0.0.28
> 
> are used in the examples projects. The packages are built with
> 
> ```shell
> ./build.sh JavaScript
> ```
> 
> and
> 
> ```shell
> ./build.sh Python
> ```
> 
> The fshafas library can be used for several targets
> 
> * in a F# program that compiles to dotnet (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli))
> * in a C# program that compiles to dotnet (see [csharp](https://github.com/bergmannjg/fshafas/blob/main/src/examples/fshafas.csharp/Program.cs))
> * in a F# program that compiles to JavaScript, the nuget package FsHafas.JavaScript is required (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli))
> * in a F# program that compiles to Python, the nuget package FsHafas.Python is required (see [cli](https://github.com/bergmannjg/fshafas/tree/main/src/examples/cli))
> * in a JavaScript program that uses the fshafas npm package (see [JS](https://github.com/bergmannjg/fshafas/tree/main/src/examples/fshafas.fable.node))
> * in a Python program that uses the fshafas python package (see [Python](https://github.com/bergmannjg/fshafas/tree/main/src/examples/fshafas.fable.python))
> 
> How will you use the library?
> 
> I added the missing packages to the current release.

![image](https://github.com/user-attachments/assets/6deac331-6c46-4549-8c1b-4f799659bb25)
![image](https://github.com/user-attachments/assets/3c5a79e1-1001-41b9-9f28-81838a14bfd7)

Thank you for your reply but when I call ./build.sh JavaScript and Python I get the same error, I've attached the screenshot below. After the build was finished, I try to build the Test but still get this error as a result, eh, not working correctly.
